[Chapter2] Project Setup
Alpha-ka-JS/React pull request #25
Opened 2021-04-01 13:01 UTC by sungwon2054

### SUMMARY

Chapter2 셋팅 관련 PR
### SCREENSHOTS OR ANIMATED GIF

2021-04-01 16:30 UTC, LeeJehwan commented on JeongSungwon/netflix/src/Components/Router.js
> +);
이게좀 거슬리네여

2021-04-01 16:31 UTC, LeeJehwan approved these changes
chapter1도 올려주세여~

2021-04-01 16:34 UTC, LeeJehwan commented on JeongSungwon/netflix/src/Components/App.js
> +import Header from "Components/Header";
에러 안나나요?

2021-04-01 16:38 UTC, LeeJehwan requested changes
수정하시고 다시 요청주세요~

2021-04-01 16:43 UTC, LeeJehwan commented
* commit mesasge에 `#` 은 안넣는것을 추천합니다. PR number가 호출됩니다.
* 2.0 Setting Up the Project에서는 npm을 이용하여 build하였고 2.1는 yarn을 쓴것으로 보입니다. 
하나로 통일 하는것을 추천드려요.  lock파일은 둘 중 하나만 있어야 합니다.

2021-05-09 13:56 UTC, LeeJehwan commented on JeongSungwon/netfilx/jsconfig.json
> +}
fix here

2021-05-09 13:57 UTC, LeeJehwan commented on JeongSungwon/netfilx/src/Components/Header.js
> +);
fix here

2021-05-09 14:04 UTC, LeeJehwan commented on JeongSungwon/netfilx/정리/Chapter2.md
> +# 2.1 React Router Part One
I recommend that you use only english and number in directory path. It maybe make some error.
but It's just only docs, so you don't have to fix this.

2021-05-09 14:07 UTC, LeeJehwan approved these changes
GOOD, please upload chapter 1 code what you practiced.

2021-05-09 14:09 UTC, sungwon2054 commented on JeongSungwon/netfilx/정리/Chapter2.md
> +# 2.1 React Router Part One
확인했습니다. 
마크다운이라 상관없다고 생각해 진행했습니다

2021-05-09 14:11 UTC, merged